import json
from app.handlers.message_handler import MessageHandler
from app.models.analysis import RawContent, HandlerResult, NuevoRescateDetails
from app.services.ai import AIService


class NuevoRescateHandler(MessageHandler):
    version = "0.1"

    def __init__(self, ai_service: AIService = None, db_service=None, whatsapp_service=None):
        super().__init__(ai_service=ai_service, db_service=db_service, whatsapp_service=whatsapp_service)
        self.ai = self.ai_service

    async def analyze(self, raw: RawContent) -> HandlerResult:
        # Call AI with template prompt + multimodal support (text + images)
        try:
            resp_text = await self.ai.run_prompt(
                "nuevo_rescate_prompt.txt", 
                {"text": raw.text or ""}, 
                images=raw.images
            )
            data = json.loads(resp_text)
            detalles = NuevoRescateDetails(**data)
        except Exception:
            detalles = None

        hr = HandlerResult()
        hr.detalles = detalles
        hr.confidence = 0.9 if detalles else 0.0
        return hr

    def validate(self, result: HandlerResult) -> HandlerResult:
        if not isinstance(result.detalles, NuevoRescateDetails):
            result.ok = False
            result.campos_faltantes = ["detalles_invalidos"]
            return result
        
        required_fields = {
            "tipo_animal": result.detalles.tipo_animal,
            "edad": result.detalles.edad,
            "color_de_pelo": result.detalles.color_de_pelo,
            "condicion_de_salud_inicial": result.detalles.condicion_de_salud_inicial,
            "ubicacion": result.detalles.ubicacion,
            "cambio_estado": result.detalles.cambio_estado,
        }
        
        missing = [k for k, v in required_fields.items() if v is None or (isinstance(v, (list, str)) and not v)]
        result.campos_faltantes = missing
        result.ok = len(missing) == 0
        return result

    async def save_to_db(self, result: HandlerResult, db_service) -> bool:
        """Save nuevo_rescate records to database. Only called when result.ok == True."""
        # Validation of result.ok is done in handle_message_flow()
        if not isinstance(result.detalles, NuevoRescateDetails):
            return False
        
        datos = result.detalles
        
        try:
            # Save animales
            animal_record = {
                "id": None,  # Generated by DB
                "nombre": datos.nombre,
                "tipo_animal": datos.tipo_animal,
                "fecha": None,
                "ubicacion": datos.ubicacion,
                "edad": datos.edad,
                "color_de_pelo": [{"color": c.color, "porcentaje": c.porcentaje} for c in datos.color_de_pelo] if datos.color_de_pelo else [],
                "condicion_de_salud_inicial": datos.condicion_de_salud_inicial,
                "activo": True,
            }
            animal_ok = db_service.insert_record(animal_record, "animales")
            if not animal_ok:
                return False
            
            # Save eventos
            evento_record = {
                "animal_id": None,
                "ubicacion_id": datos.cambio_estado.ubicacion_id if datos.cambio_estado else None,
                "estado_id": datos.cambio_estado.estado_id if datos.cambio_estado else None,
                "persona": datos.cambio_estado.persona if datos.cambio_estado else None,
                "tipo_relacion_id": datos.cambio_estado.tipo_relacion_id if datos.cambio_estado else None,
                "fecha": None,
            }
            evento_ok = db_service.insert_record(evento_record, "eventos")
            return evento_ok
        except Exception:
            return False
